version: '2.2'

services:
  devver:
    container_name: chudo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_HTTP_TIMEOUT=8000
    tty: true